kind: pipeline
type: docker
name: default

steps:
- name: build
  image: docker:git
  commands:
    - git clone https://github.com/mgossman71/gozznet-old.git
    - cd gozznet-old;docker build . -t mgossman71/gozznet-old:drone
    - docker push mgossman71/gozznet-old:drone
